Repository WildCodeSchool/202209-orleans-php-project-externatic, pull requests merged in 2022-12, with the labels that each got.

#58 S0_init
  assets/styles/_root.scss
  assets/styles/app.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#59 S1US05_Part1 - User log & User informations
  assets/styles/_root.scss
  config/packages/security.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  migrations/Version20221212101031.php
  public/uploads/images/avatar/.gitignore
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  templates/registration/register.html.twig
Labels: Reviewed, Correction Done

#60 S1US05_part2 UPLOAD FILE
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  symfony.lock
Labels: Reviewed, Correction Done

#74 S02US11 show profil with fixtures
  composer.json
  composer.lock
  migrations/Version20221214084025.php
  src/Controller/CandidateController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidate.php
  src/Entity/User.php
  src/Form/CandidateType.php
  src/Repository/CandidateRepository.php
  templates/candidate/_form.html.twig
  templates/candidate/edit.html.twig
  templates/candidate/show.html.twig
  templates/dashboard_layout.html.twig
Labels: Reviewed, Correction Done

#78 DEV TO MAIN
  assets/app.js
  assets/images/logo_externatic.svg
  assets/styles/_root.scss
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20221212101031.php
  migrations/Version20221214084025.php
  package.json
  public/uploads/images/avatar/.gitignore
  src/Controller/CandidateController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidate.php
  src/Entity/User.php
  src/Form/CandidateType.php
  src/Form/RegistrationFormType.php
  src/Repository/CandidateRepository.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/base.html.twig
  templates/candidate/_form.html.twig
  templates/candidate/edit.html.twig
  templates/candidate/show.html.twig
  templates/component/_navigation_bar.html.twig
  templates/dashboard_layout.html.twig
  templates/home/index.html.twig
  templates/registration/register.html.twig
  templates/svg/_logo.svg.twig
  yarn.lock
Labels: Reviewed, Priority

#82 S02US11 added user profil picture
  assets/images/Placeholder-pp.png
  assets/styles/_profil.scss
  assets/styles/app.scss
  templates/candidate/show.html.twig
Labels: Reviewed

#92 FIX Bad Route Name
  src/Controller/RegistrationController.php
Labels: Reviewed, Priority High

#77 US01 make view showing all job offers
  assets/styles/_root.scss
  assets/styles/card.scss
  composer.lock
  migrations/Version20221214131251.php
  src/Controller/OfferController.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/Offer.php
  src/Form/OfferType.php
  src/Repository/OfferRepository.php
  templates/component/_card.html.twig
  templates/offer/_delete_form.html.twig
  templates/offer/_form.html.twig
  templates/offer/edit.html.twig
  templates/offer/index.html.twig
  templates/offer/new.html.twig
  templates/offer/show.html.twig
  webpack.config.js
Labels: Conflict Resolve, Priority High

#88 S1US45_part1 Entreprise show by_id
  migrations/Version20221215183101.php
  src/Controller/CompanyController.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Form/CompanyType.php
  src/Repository/CompanyRepository.php
  templates/company/_delete_form.html.twig
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/company/show.html.twig
Labels: Reviewed

#91 S1US08_Footer
  assets/styles/_root.scss
  templates/base.html.twig
  templates/component/_footer.html.twig
  templates/svg/_wave.svg.twig
Labels: Reviewed

#93 DEV TO MAIN
  assets/images/Placeholder-pp.png
  assets/styles/_profil.scss
  assets/styles/_root.scss
  assets/styles/app.scss
  assets/styles/card.scss
  composer.lock
  migrations/Version20221214131251.php
  migrations/Version20221215183101.php
  src/Controller/CompanyController.php
  src/Controller/OfferController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/Company.php
  src/Entity/Offer.php
  src/Form/CompanyType.php
  src/Form/OfferType.php
  src/Repository/CompanyRepository.php
  src/Repository/OfferRepository.php
  templates/base.html.twig
  templates/candidate/show.html.twig
  templates/company/_delete_form.html.twig
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/company/show.html.twig
  templates/component/_card.html.twig
  templates/component/_footer.html.twig
  templates/offer/_delete_form.html.twig
  templates/offer/_form.html.twig
  templates/offer/edit.html.twig
  templates/offer/index.html.twig
  templates/offer/new.html.twig
  templates/offer/show.html.twig
  templates/svg/_wave.svg.twig
  webpack.config.js
Labels: Reviewed

#94 FIX migration fail
  migrations/Version20221214131251.php
Labels: Reviewed, Priority High

#97 FIX changes after demo feedback
  src/Controller/CandidateController.php
  templates/candidate/show.html.twig
Labels: Reviewed, Priority High

#96 FIX bootstrap surcharge issue
  assets/styles/_root.scss
Labels: Reviewed

#84 S2US56 Adding Sidebar
  assets/styles/_root.scss
  assets/styles/_wcs.scss
  assets/styles/app.scss
  assets/styles/dashboard.scss
  templates/candidate/show.html.twig
  templates/component/_sideBar_dashboard.html.twig
  templates/dashboard_layout.html.twig
  webpack.config.js
Labels: Reviewed, Conflict Resolve

#106 FIX Root _ conflict mistake
  assets/styles/_root.scss
Labels: Reviewed, Priority High

#87 S02US12 added edit profil
  assets/styles/_root.scss
  src/Controller/CandidateController.php
  src/Entity/Candidate.php
  src/Form/CandidateType.php
  src/Form/UserType.php
  templates/_flashes.html.twig
  templates/candidate/_form.html.twig
  templates/candidate/edit.html.twig
  templates/dashboard_layout.html.twig
Labels: Reviewed, Conflict Resolve

#105 Fix Une Navbar pour tous
  templates/base.html.twig
  templates/company/show.html.twig
  templates/dashboard_layout.html.twig
  templates/home/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Conflict Resolve

#104 S03 US47 work experiences
  assets/images/default_avatar.png
  assets/styles/_profil.scss
  migrations/Version20221216203942.php
  src/Controller/CandidateController.php
  src/Controller/ExperienceController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/Entity/Candidate.php
  src/Entity/Experience.php
  src/Form/ExperienceType.php
  src/Repository/ExperienceRepository.php
  templates/candidate/_profil.html.twig
  templates/candidate/show.html.twig
  templates/experience/_delete_form.html.twig
  templates/experience/_form.html.twig
  templates/experience/_index.html.twig
  templates/experience/edit.html.twig
  templates/experience/new.html.twig
Labels: Reviewed

#111 fix vich aupload
  src/Entity/User.php
  templates/candidate/_profil.html.twig
Labels: Reviewed

#109 S03 us48 profil education
  migrations/Version20221219123717.php
  src/Controller/EducationController.php
  src/DataFixtures/EducationFixtures.php
  src/Entity/Candidate.php
  src/Entity/Education.php
  src/Form/EducationType.php
  src/Repository/EducationRepository.php
  templates/candidate/show.html.twig
  templates/dashboard_layout.html.twig
  templates/education/_delete_form.html.twig
  templates/education/_form.html.twig
  templates/education/_index.html.twig
  templates/education/edit.html.twig
  templates/education/index.html.twig
  templates/education/new.html.twig
  templates/education/show.html.twig
Labels: Reviewed, Conflict Resolve

#108 S3 US45 Add offer list to the Company page
  migrations/Version20221219160736.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/Company.php
  src/Entity/Offer.php
  templates/company/show.html.twig
Labels: Reviewed, Conflict Resolve
