Repository WildCodeSchool/202209-orleans-php-project-externatic, pull requests merged in 2023-01, with the labels that each got.

#114 S03US12 added preview avatar
  assets/preview.js
  assets/styles/_profil.scss
  src/Controller/CandidateController.php
  src/Form/RegistrationFormType.php
  templates/candidate/_form.html.twig
  templates/candidate/edit.html.twig
  templates/dashboard_layout.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: Reviewed, Correction Done

#117 S3US02 - Offer ID info
  templates/offer/show.html.twig
Labels: Reviewed

#110 Us03 fonction recherche par mot cle
  src/Controller/OfferController.php
  src/Form/SearchOfferType.php
  src/Repository/OfferRepository.php
  templates/offer/index.html.twig
Labels: Reviewed, Correction Done

#113 FIX problems mobile view
  assets/styles/_profil.scss
  assets/styles/dashboard.scss
  templates/candidate/_profil.html.twig
  templates/candidate/show.html.twig
  templates/component/_navigation_bar.html.twig
  templates/component/_sideBar_dashboard.html.twig
  templates/dashboard_layout.html.twig
  templates/education/_index.html.twig
  templates/experience/_index.html.twig
  templates/svg/_logo.svg.twig
Labels: Reviewed, Conflict Resolve

#126 S03US13 edit experience
  src/Controller/ExperienceController.php
  src/Form/ExperienceType.php
  templates/experience/_form.html.twig
  templates/experience/edit.html.twig
Labels: Reviewed

#128 FIX sidebar in edit profil
  templates/candidate/edit.html.twig
Labels: Reviewed

#129 FIX edit profil, add back to
  templates/candidate/_form.html.twig
Labels: Reviewed

#130 Fix Date_offerID
  templates/offer/show.html.twig
Labels: Reviewed

#122 S3US40 Offer Creation
  migrations/Version20230103144818.php
  src/Controller/OfferController.php
  src/Entity/Offer.php
  src/Form/OfferType.php
  templates/dashboard_layout.html.twig
  templates/offer/_form.html.twig
  templates/offer/new.html.twig
Labels: Reviewed, Conflict Resolve

#124 US28 => vue de toutes les offres sur le Dashboard
  src/Controller/OfferController.php
  templates/component/_card.html.twig
  templates/offer/showAll.html.twig
Labels: Reviewed, Correction Done

#132 FIX dates experiences
  src/Form/ExperienceType.php
Labels: Reviewed

#135 US39 Delete Offer
  src/Controller/OfferController.php
  templates/offer/_delete_form.html.twig
  templates/offer/_form.html.twig
  templates/offer/show.html.twig
Labels: Reviewed

#125 S03US06_Login/Logout
  config/packages/security.yaml
  src/Controller/LoginController.php
  src/Controller/SecurityController.php
  templates/component/_navigation_bar.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Conflict Resolve

#139 S03US14 edit education
  src/Controller/EducationController.php
  src/Form/EducationType.php
  templates/education/_form.html.twig
  templates/education/_index.html.twig
  templates/education/edit.html.twig
  templates/education/index.html.twig
  templates/education/show.html.twig
Labels: Reviewed

#138 FIX Style
  assets/styles/_root.scss
  templates/candidate/show.html.twig
  templates/component/_sideBar_dashboard.html.twig
  templates/dashboard_layout.html.twig
Labels: Reviewed, Correction Done

#140 US02 => isImportant
  assets/styles/_root.scss
  src/Form/OfferType.php
  templates/component/_card.html.twig
  templates/offer/show.html.twig
Labels: Reviewed

#142 FIX education changed style
  templates/education/_index.html.twig
Labels: Reviewed

#143 FIX annual wage info
  templates/offer/show.html.twig
Labels: Reviewed, Conflict Resolve

#144 FIX add flash delete experience
  src/Controller/ExperienceController.php
Labels: Reviewed

#131 S03US63 added contract type
  assets/styles/_profil.scss
  migrations/Version20230104084435.php
  src/DataFixtures/ContractFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/Entity/Contract.php
  src/Entity/Experience.php
  src/Repository/ContractRepository.php
  templates/experience/_index.html.twig
Labels: Reviewed, Conflict Resolve

#146 S03US53 delete education
  src/Controller/EducationController.php
  templates/education/_delete_form.html.twig
  templates/education/_index.html.twig
Labels: Reviewed

#155 fixed route after login
  src/Controller/LoginController.php
  templates/login/index.html.twig
Labels: Reviewed

#159 US07 - First part of home page => Présentation
  assets/images/fusee.png
  assets/images/hello.png
  assets/images/sablier.png
  templates/home/index.html.twig
  templates/svg/_ellipse.svg.twig
Labels: Reviewed

#161 fix style input & button login page
  templates/login/index.html.twig
Labels: Reviewed

#160 S03US51_add_experience
  src/Controller/ExperienceController.php
  src/Entity/Experience.php
  src/Form/ExperienceType.php
  templates/candidate/show.html.twig
  templates/experience/_form.html.twig
  templates/experience/_index.html.twig
  templates/experience/new.html.twig
Labels: Reviewed

#156 Us18 se porter candidat
  config/packages/framework.yaml
  migrations/Version20230104100014.php
  src/Controller/CandidateController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/EducationFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidate.php
  src/Entity/Offer.php
  templates/offer/show.html.twig
Labels: Reviewed, Conflict Resolve

#164 S03 us52b add contract type
  src/Entity/Contract.php
  src/Form/ExperienceType.php
Labels: Reviewed

#165 DEV TO MAIN
  assets/images/fusee.png
  assets/images/hello.png
  assets/images/sablier.png
  assets/styles/home.scss
  config/packages/framework.yaml
  migrations/Version20230104100014.php
  src/Controller/CandidateController.php
  src/Controller/ExperienceController.php
  src/Controller/LoginController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/EducationFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidate.php
  src/Entity/Contract.php
  src/Entity/Experience.php
  src/Entity/Offer.php
  src/Form/ExperienceType.php
  templates/candidate/show.html.twig
  templates/experience/_form.html.twig
  templates/experience/_index.html.twig
  templates/experience/new.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/offer/show.html.twig
  templates/svg/_ellipse.svg.twig
  webpack.config.js
Labels: Reviewed

#166 FIX datetime interface
  src/Entity/Experience.php
Labels: Reviewed

#167 FIX navbar link
  templates/component/_navigation_bar.html.twig
Labels: Reviewed

#168 FIX light fix of the footer
  templates/component/_footer.html.twig
Labels: Reviewed

#170 FIX toggle enddate
  assets/app.js
  assets/endDate.js
Labels: Reviewed

#169 FIX link to my profile in sidebar
  templates/component/_sideBar_dashboard.html.twig
Labels: Reviewed

#163 US07 part3 => Adding search bar to home
  assets/images/home-bg.jpg
  assets/styles/_root.scss
  assets/styles/home.scss
  src/Controller/HomeController.php
  templates/component/_searchBar.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
  templates/svg/_rounded.svg.twig
  webpack.config.js
Labels: Reviewed, Conflict Resolve, Priority High

#172 FIX remove double declaration addentry
  webpack.config.js
Labels: Reviewed

#173 FIX fixtures contract expe
  src/DataFixtures/ExperienceFixtures.php
  src/Entity/Contract.php
  templates/experience/_index.html.twig
Labels: Reviewed

#174 FIX avatar preview registration
  assets/previewRegistration.js
  templates/registration/register.html.twig
  webpack.config.js
Labels: Reviewed, Priority High

#175 DEV TO MAIN
  assets/previewRegistration.js
  src/DataFixtures/ExperienceFixtures.php
  src/Entity/Contract.php
  templates/experience/_index.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: Reviewed

#183 DEV TO MAIN
  assets/app.js
  templates/experience/edit.html.twig
  templates/experience/new.html.twig
  webpack.config.js
Labels: Reviewed

#186 FIX Offer -> adding button 'add offer'
  templates/offer/showAll.html.twig
Labels: Reviewed

#193 FIX add delete in edit experience
  templates/experience/edit.html.twig
Labels: Reviewed

#192 FIX redirection after edit profil
  src/Controller/CandidateController.php
Labels: Reviewed

#191 Fix end date is current position
  src/Entity/Experience.php
Labels: Reviewed, Correction Done

#182 Us30 offres candidat
  src/Controller/CandidateController.php
  templates/candidate/showMyApplications.html.twig
  templates/component/_sideBar_dashboard.html.twig
  templates/offer/show.html.twig
Labels: Reviewed

#189 US17 voir les candidatures en tant que consultant
  migrations/Version20230107144107.php
  src/Controller/RecruiterController.php
  src/DataFixtures/RecruiterFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Recruiter.php
  src/Entity/User.php
  src/Repository/RecruiterRepository.php
  templates/component/_card_candidate.html.twig
  templates/recruiter/index.html.twig
  templates/recruiter/showApplications.html.twig
Labels: Reviewed

#194 FIX job title
  templates/experience/_index.html.twig
Labels: Reviewed, Correction Done

#200 FIX routing
  templates/component/_sideBar_dashboard.html.twig
Labels: Reviewed, Priority High

#203 FIX space in search
  src/Controller/HomeController.php
  src/Controller/OfferController.php
Labels: Reviewed

#190 FIX sort reverse experience
  src/Entity/Candidate.php
Labels: Reviewed, Correction Done

#199 S04 us16 upload cv
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20230109183210.php
  public/uploads/files/cv/.gitignore
  src/Entity/Candidate.php
  src/Form/CandidateType.php
  templates/component/_sideBar_dashboard.html.twig
Labels: Reviewed, Correction Done

#205 modif user
  src/Controller/CandidateController.php
  src/Controller/OfferController.php
  templates/offer/isLogShow.html.twig
  templates/offer/show.html.twig
Labels: Reviewed

#206 FIX inscription
  templates/login/index.html.twig
Labels: Reviewed

#208 FIX login
  templates/registration/register.html.twig
Labels: Reviewed

#198 Fix dashboard style
  assets/dashboard.js
  assets/styles/_root.scss
  assets/styles/dashboard.scss
  templates/candidate/show.html.twig
  templates/component/_sideBar_dashboard.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
  templates/dashboard_layout.html.twig
  templates/svg/_logo_dashboard.svg.twig
  templates/svg/_logo_dashboard_mobile.svg.twig
  webpack.config.js
Labels: Reviewed, Conflict Resolve

#210 FIX scss
  assets/styles/dashboard.scss
Labels: Reviewed, Priority High

#207 FIX serialized pb
  src/Entity/User.php
Labels: Reviewed

#209 FIX inscription new candidat
  migrations/Version20230110130454.php
  src/Controller/RegistrationController.php
  src/Entity/Candidate.php
Labels: Reviewed, Correction Done

#211 FIX Adding searchbar to offer Page and fix nav issue
  src/Controller/OfferController.php
  templates/component/_navigation_bar.html.twig
  templates/offer/showAll.html.twig
Labels: Reviewed

#212 DEV TO MAIN
  assets/dashboard.js
  assets/styles/_profil.scss
  assets/styles/_root.scss
  assets/styles/app.scss
  assets/styles/card.scss
  assets/styles/dashboard.scss
  assets/styles/home.scss
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20230107144107.php
  migrations/Version20230109183210.php
  migrations/Version20230110130454.php
  public/uploads/files/.gitignore
  public/uploads/files/cv/.gitignore
  src/Controller/CandidateController.php
  src/Controller/EducationController.php
  src/Controller/HomeController.php
  src/Controller/LoginController.php
  src/Controller/OfferController.php
  src/Controller/RecruiterController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/EducationFixtures.php
  src/DataFixtures/RecruiterFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidate.php
  src/Entity/Education.php
  src/Entity/Experience.php
  src/Entity/Recruiter.php
  src/Entity/User.php
  src/Form/CandidateType.php
  src/Form/EducationType.php
  src/Repository/RecruiterRepository.php
  templates/candidate/show.html.twig
  templates/candidate/showMyApplications.html.twig
  templates/component/_card.html.twig
  templates/component/_card_candidate.html.twig
  templates/component/_navigation_bar.html.twig
  templates/component/_sideBar_dashboard.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
  templates/component/offerShow.html.twig
  templates/dashboard_layout.html.twig
  templates/education/_form.html.twig
  templates/education/_index.html.twig
  templates/education/new.html.twig
  templates/experience/_index.html.twig
  templates/experience/edit.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/offer/index.html.twig
  templates/offer/isLogShow.html.twig
  templates/offer/isNotLogShow.html.twig
  templates/offer/show.html.twig
  templates/offer/showAll.html.twig
  templates/recruiter/index.html.twig
  templates/recruiter/showApplications.html.twig
  templates/registration/register.html.twig
  templates/svg/_localisation.svg.twig
  templates/svg/_logo_dashboard.svg.twig
  templates/svg/_logo_dashboard_mobile.svg.twig
  webpack.config.js
Labels: Reviewed

#221 style_FIX Add more colors to Make Coloriage Great Again
  assets/styles/_root.scss
  assets/styles/app.scss
  templates/dashboard_layout.html.twig
Labels: Reviewed

#222 FIX_Input Style
  assets/styles/_root.scss
  assets/styles/app.scss
Labels: Reviewed

#223 FIX flash location
  templates/dashboard_layout.html.twig
Labels: Reviewed

#230 FIX link upload CV
  templates/candidate/_form.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
Labels: Reviewed

#214 US68 => Sidebar recruiter
  src/Controller/RecruiterController.php
  templates/component/_navigation_bar.html.twig
  templates/component/_sideBar_dashboard.html.twig
  templates/component/_sidenav_dashboard_recruiter.html.twig
  templates/recruiter/applications.html.twig
  templates/recruiter/showApplications.html.twig
Labels: To review, Correction Done

#218 US29 => show all entreprises
  src/Controller/CompanyController.php
  templates/company/index.html.twig
Labels: Reviewed, Correction Done

#229 S04US66 secure path with roles
  config/packages/security.yaml
  src/Controller/OfferController.php
Labels: Reviewed, Conflict Resolve

#232 Fix app user candidat
  src/Controller/CandidateController.php
  templates/candidate/_form.html.twig
  templates/candidate/_profil.html.twig
  templates/component/_navigation_bar.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
  templates/education/_form.html.twig
  templates/experience/_form.html.twig
Labels: Reviewed, Conflict Resolve

#231 US07 => Adding Sponsor Carrousel
  assets/home.js
  assets/styles/home.scss
  migrations/Version20230116155009.php
  src/Controller/HomeController.php
  src/DataFixtures/SponsorsFixtures.php
  src/Entity/Sponsor.php
  src/Form/SponsorType.php
  src/Repository/SponsorRepository.php
  templates/home/_sponsor.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#233 FIX Cleaning code
  assets/styles/dashboard.scss
  templates/component/_sideBar_dashboard.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
  templates/component/_sidenav_dashboard_recruiter.html.twig
Labels: Reviewed, Conflict Resolve

#235 US41 accepter ou refuser une candidature
  migrations/Version20230116092314.php
  src/Controller/CandidateController.php
  src/Controller/RecruiterController.php
  src/DataFixtures/CandidateFixtures.php
  src/Entity/Application.php
  src/Entity/Candidate.php
  src/Entity/Offer.php
  src/Form/ApplicationResponseType.php
  src/Repository/ApplicationRepository.php
  templates/component/_card_candidate.html.twig
  templates/recruiter/applicationDecision.html.twig
  templates/recruiter/applications.html.twig
  templates/recruiter/showApplications.html.twig
Labels: Reviewed, Conflict Resolve

#236 FIX route
  src/Controller/LoginController.php
Labels: Reviewed

#237 Fix redirection url it not good candidate
  src/Controller/EducationController.php
  src/Controller/ExperienceController.php
  templates/component/_sidenav_dashboard_candidate.html.twig
  templates/experience/_index.html.twig
Labels: Reviewed, Conflict Resolve

#238 US30 candidat voit ses candidatures et leur statuts
  src/Controller/CandidateController.php
  src/Entity/Application.php
  src/Entity/Candidate.php
  templates/candidate/showMyApplications.html.twig
  templates/component/_card.html.twig
Labels: Reviewed, Correction Done

#239 S04US15 added is favorite
  assets/app.js
  assets/favorite.js
  migrations/Version20230118110237.php
  package.json
  src/Controller/CandidateController.php
  src/Entity/Candidate.php
  src/Entity/Offer.php
  templates/component/_card.html.twig
  templates/component/offerShow.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed, Conflict Resolve

#241 styleFIX => Form size
  templates/candidate/edit.html.twig
  templates/education/edit.html.twig
  templates/education/new.html.twig
  templates/experience/edit.html.twig
  templates/experience/new.html.twig
Labels: Reviewed

#243 US35 => Company create
  src/Form/CompanyType.php
  templates/company/new.html.twig
Labels: Reviewed

#244 US29 => Adding Delete and Style
  templates/company/_delete_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
Labels: Reviewed

#240 styleFix => Profil page
  assets/styles/_profil.scss
  assets/styles/_root.scss
  assets/styles/app.scss
  templates/candidate/_profil.html.twig
  templates/dashboard_layout.html.twig
  templates/education/_delete_form.html.twig
  templates/education/_index.html.twig
  templates/experience/_delete_form.html.twig
  templates/experience/_index.html.twig
Labels: Reviewed, Conflict Resolve

#246 FIX_conflictmiss
  templates/experience/_index.html.twig
Labels: Reviewed

#248 added show favorite
  src/Controller/CandidateController.php
  templates/candidate/showFavorite.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
Labels: Reviewed

#249 US66 => Affichage de la page du compte
  src/Controller/AccountController.php
  templates/account/index.html.twig
  templates/component/_sideBar_dashboard.html.twig
Labels: Reviewed

#251 FIX route
  config/packages/security.yaml
  templates/component/_navigation_bar.html.twig
  templates/component/_sidenav_dashboard_recruiter.html.twig
Labels: Reviewed

#253 FIX heigth card
  assets/styles/card.scss
  templates/component/_card.html.twig
Labels: Reviewed

#252 FIX authorizations
  src/Controller/OfferController.php
Labels: Reviewed, Correction Done

#256 FIX link apply to a job
  src/Controller/CandidateController.php
  templates/component/_sidenav_dashboard_candidate.html.twig
Labels: Reviewed

#259 styleFIX => Offers
  templates/offer/_form.html.twig
  templates/offer/isLogShow.html.twig
  templates/offer/isNotLogShow.html.twig
  templates/offer/show.html.twig
  templates/offer/showAll.html.twig
Labels: Reviewed

#260 FIX recruiter apply
  src/Form/ApplicationResponseType.php
  templates/recruiter/applicationDecision.html.twig
Labels: Reviewed

#261 FIX_Link
  templates/component/_navigation_bar.html.twig
Labels: Reviewed

#262 fix route login
  src/Controller/LoginController.php
Labels: Reviewed

#254 US67 => Page Profil Publique
  assets/styles/_root.scss
  src/Controller/ProfilController.php
  templates/component/_educationSection.html.twig
  templates/component/_experienceSection.html.twig
  templates/education/_index.html.twig
  templates/experience/_index.html.twig
  templates/profil/show.html.twig
Labels: Reviewed, Priority High

#263 fix_view candidate
  templates/recruiter/showApplications.html.twig
Labels: Reviewed

#264 dev to main
  templates/recruiter/showApplications.html.twig
Labels: Reviewed

#268 styleFix application
  src/Controller/RecruiterController.php
  templates/component/_card.html.twig
  templates/component/_card_candidate.html.twig
  templates/offer/index.html.twig
  templates/offer/isNotLogShow.html.twig
  templates/offer/showAll.html.twig
  templates/recruiter/applicationDecision.html.twig
  templates/recruiter/applications.html.twig
  templates/recruiter/showApplications.html.twig
Labels: Reviewed

#273 FIX light fix of the offer card color
  assets/styles/_root.scss
Labels: Reviewed

#265 S04US15 notification candidate
  src/Controller/CandidateController.php
  templates/component/_sideBar_dashboard.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
Labels: Reviewed

#271 style_FIX profil title section
  templates/education/_index.html.twig
  templates/experience/_index.html.twig
Labels: Reviewed

#272 FIX company style and delete issue
  src/Controller/CompanyController.php
  src/Entity/Company.php
  templates/company/index.html.twig
Labels: Reviewed, Correction Done

#275 Fix style favorite
  assets/favorite.js
  templates/candidate/showFavorite.html.twig
  templates/component/_card.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
Labels: Reviewed, Conflict Resolve

#278 US67 => Add Offer WhatYouSeeIsWhatYouGet :-)
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  config/packages/twig.yaml
  package.json
  src/Form/OfferType.php
  symfony.lock
  templates/component/offerShow.html.twig
  templates/offer/show.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#280 FIX offer style v3444
  templates/candidate/showMyApplications.html.twig
  templates/component/_card.html.twig
  templates/offer/index.html.twig
Labels: Reviewed

#284 Fix mobile view profil
  templates/account/index.html.twig
  templates/candidate/_profil.html.twig
Labels: Reviewed

#285 Fix roles
  templates/admin/index.html.twig
Labels: Reviewed

#283 S05 us21 admin delete
  src/Controller/AdminUserController.php
  src/Entity/Candidate.php
  templates/admin/_delete_form.html.twig
Labels: Reviewed

#287 US68_recruteur_gerer_skills_offres
  migrations/Version20230124143304.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/Entity/Offer.php
  src/Entity/Skill.php
  src/Form/OfferType.php
  templates/component/_card.html.twig
  templates/component/offerShow.html.twig
Labels: Reviewed

#290 FIX changing roles
  src/Controller/AdminUserController.php
  templates/admin/index.html.twig
  templates/admin/new.html.twig
  templates/base.html.twig
Labels: Reviewed

#293 FIX keep at least one admin
  src/Controller/AdminUserController.php
  src/Repository/UserRepository.php
Labels: Reviewed

#294 FIX fontsize
  assets/styles/_root.scss
  assets/styles/app.scss
Labels: Reviewed

#295 FIX remove add user
  templates/admin/index.html.twig
Labels: Reviewed

#296 FIX no favories
  templates/candidate/showFavorite.html.twig
Labels: Reviewed

#297 FIX no application
  templates/candidate/showMyApplications.html.twig
Labels: Reviewed

#300 FIX improved condition
  templates/candidate/showFavorite.html.twig
  templates/candidate/showMyApplications.html.twig
Labels: Reviewed

#291 Us42 part 1 => Adding geolocalisation
  composer.lock
  migrations/Version20230125111344.php
  src/Controller/HomeController.php
  src/Controller/OfferController.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/Entity/Offer.php
  src/Services/Geolocalisation.php
Labels: Reviewed, Conflict Resolve

#292 US59_recruteur_appropriation_offer
  migrations/Version20230125092343.php
  src/Controller/OfferController.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/DataFixtures/RecruiterFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Offer.php
  src/Entity/Recruiter.php
  src/Form/OfferType.php
  templates/component/_card.html.twig
Labels: Reviewed, Conflict Resolve

#306 S05 us61 reset password
  composer.json
  composer.lock
  config/bundles.php
  config/packages/mailer.yaml
  config/packages/reset_password.yaml
  config/services.yaml
  migrations/Version20230126124151.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/login/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Reviewed

#307 Us42 => searchbar loc
  assets/rangeSearchbar.js
  src/Controller/HomeController.php
  src/Controller/OfferController.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/GpsPositionInterface.php
  src/Entity/Offer.php
  src/Entity/SearchOfferModule.php
  src/Form/SearchOfferType.php
  src/Repository/OfferRepository.php
  src/Services/DistanceCalculator.php
  src/Services/Geolocalisation.php
  src/Services/OfferFounder.php
  templates/component/_searchBar.html.twig
  webpack.config.js
Labels: Reviewed, Conflict Resolve, Priority High

#310 USNAVY dashboard candidate
  src/Controller/CandidateController.php
  src/Repository/ApplicationRepository.php
  src/Repository/CandidateRepository.php
  src/Services/Completion.php
  templates/candidate/showDashboard.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
Labels: Reviewed

#311 USAIRFORCE Show Recruiter Offer
  src/Controller/RecruiterController.php
  templates/component/_sidenav_dashboard_recruiter.html.twig
  templates/offer/showAll.html.twig
  templates/recruiter/showMyOffer.html.twig
Labels: Reviewed

#312 Fix acces denie
  assets/preview.js
  src/Controller/RecruiterController.php
  src/Form/RecruiterType.php
  templates/account/index.html.twig
  templates/recruiter/profilEdit.html.twig
Labels: Reviewed, Conflict Resolve

#318 FIX_link_CV
  templates/component/_sidenav_dashboard_candidate.html.twig
Labels: Reviewed

#314 US63 dashboard recruiter
  src/Controller/RecruiterController.php
  src/Services/ApplyStatus.php
  templates/component/_sidenav_dashboard_recruiter.html.twig
  templates/recruiter/showDashboard.html.twig
Labels: Reviewed, Conflict Resolve

#317 FIX link tile candidate
  src/Controller/CandidateController.php
  templates/candidate/showDashboard.html.twig
  templates/candidate/showMyAcceptedApplications.html.twig
Labels: Reviewed, Correction Done

#316 US70 => Adding map to the offer show
  assets/mapOfferShow.js
  assets/styles/app.scss
  package.json
  templates/component/_mapShowOffer.html.twig
  templates/offer/isLogShow.html.twig
  templates/offer/isNotLogShow.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed, Correction Done

#320 pataFIX_postalCode
  src/DataFixtures/OfferFixtures.php
Labels: Reviewed

#321 Dave2Maine
  assets/mapOfferShow.js
  assets/preview.js
  assets/styles/app.scss
  package.json
  src/Controller/CandidateController.php
  src/Controller/RecruiterController.php
  src/DataFixtures/OfferFixtures.php
  src/Form/RecruiterType.php
  src/Repository/ApplicationRepository.php
  src/Repository/CandidateRepository.php
  src/Services/ApplyStatus.php
  src/Services/Completion.php
  templates/account/index.html.twig
  templates/candidate/showDashboard.html.twig
  templates/candidate/showMyAcceptedApplications.html.twig
  templates/component/_mapShowOffer.html.twig
  templates/component/_sidenav_dashboard_candidate.html.twig
  templates/component/_sidenav_dashboard_recruiter.html.twig
  templates/offer/isLogShow.html.twig
  templates/offer/isNotLogShow.html.twig
  templates/offer/showAll.html.twig
  templates/recruiter/profilEdit.html.twig
  templates/recruiter/showDashboard.html.twig
  templates/recruiter/showMyOffer.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#335 FIX progress bar
  templates/candidate/showDashboard.html.twig
Labels: Reviewed

#336 FIX read me
  README.md
Labels: Reviewed

#337 Fix registration center
  templates/registration/register.html.twig
Labels: Reviewed

#338 FIX login
  templates/login/index.html.twig
Labels: Reviewed

#339 Us N Bolt map on all Offers
  assets/mapShowAllOffers.js
  composer.lock
  src/Controller/HomeController.php
  src/Controller/OfferController.php
  src/Services/OfferToJson.php
  symfony.lock
  templates/offer/index.html.twig
  templates/offer/showAll.html.twig
  webpack.config.js
Labels: Reviewed

#340 Daiv to Mayne
  README.md
  assets/mapShowAllOffers.js
  composer.lock
  src/Controller/HomeController.php
  src/Controller/OfferController.php
  src/Services/OfferToJson.php
  symfony.lock
  templates/candidate/showDashboard.html.twig
  templates/login/index.html.twig
  templates/offer/index.html.twig
  templates/offer/showAll.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: Reviewed
